-- 創建資料庫
CREATE DATABASE `YOKULT`;

USE `YOKULT`;

-- 員工資料
DROP TABLE IF EXISTS `SHIFT_SCHEDULE`;

CREATE TABLE `SHIFT_SCHEDULE` (
`SCHEDULE_DATE` DATE NOT NULL COMMENT '日期',
  `STAFF_ID` varchar(50) NOT NULL COMMENT '員工編號',
  `TYPEOFLEAVE` varchar(50) NOT NULL COMMENT '假別',
  `MORNINGSHIFT_NIGHTSHIFT` varchar(50) NOT NULL COMMENT '早班晚班',
  FOREIGN KEY (`SCHEDULE_DATE`)
  REFERENCES `SCHEDULE` (`SCHEDULE_DATE`),
  FOREIGN KEY (`STAFF_ID`)
  REFERENCES `STAFF` (`STAFF_ID`))
  comment = '排班';

INSERT INTO 
  `SHIFT_SCHEDULE` (`SCHEDULE_DATE`, `STAFF_ID`, `TYPEOFLEAVE`, `MORNINGSHIFT_NIGHTSHIFT`)
VALUES
  ('2022-08-01', 'TGA001', 'ANNUAL_LEAVE', '早班'),
  ('2022-08-02', 'TGA002', 'PERSONAL_LEAVE', '晚班'),
  ('2022-08-03', 'TGA003', 'OFFICIAL_LEAVE', '早班');
